package es.home.recetario.dto;

// Generated 19-nov-2011 18:20:01 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Receta generated by hbm2java
 */
@Entity
@Table(name = "receta", catalog = "cocina")
public class RecetaDTO implements java.io.Serializable {

    private static final long serialVersionUID = 6210631412420659977L;

    private Integer idReceta;
    private String nombre;
    private String datos;
    private String cantidades;
    private Set<RelRectIngDTO> relRectIngs = new HashSet<RelRectIngDTO>(0);

    public RecetaDTO() {
	super();
    }

    public RecetaDTO(final String nombre, final String datos) {
	this.nombre = nombre;
	this.datos = datos;
    }

    public RecetaDTO(final String nombre, final String datos, final Set<RelRectIngDTO> relRectIngs) {
	this.nombre = nombre;
	this.datos = datos;
	this.relRectIngs = relRectIngs;
    }

    @Column(name = "cantidades", nullable = false, length = 400)
    public String getCantidades() {
	return this.cantidades;
    }

    @Column(name = "datos", nullable = false, length = 400)
    public String getDatos() {
	return this.datos;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id_receta", unique = true, nullable = false)
    public Integer getIdReceta() {
	return this.idReceta;
    }

    @Column(name = "nombre", nullable = false, length = 45)
    public String getNombre() {
	return this.nombre;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "receta", cascade = CascadeType.ALL, orphanRemoval=true)
    public Set<RelRectIngDTO> getRelRectIngs() {
	return this.relRectIngs;
    }

    public void setCantidades(final String cantidades) {
	this.cantidades = cantidades;
    }

    public void setDatos(final String datos) {
	this.datos = datos;
    }

    public void setIdReceta(final Integer idReceta) {
	this.idReceta = idReceta;
    }

    public void setNombre(final String nombre) {
	this.nombre = nombre;
    }

    public void setRelRectIngs(final Set<RelRectIngDTO> relRectIngs) {
	this.relRectIngs = relRectIngs;
    }

}
