package es.home.recetario.dto;

// Generated 19-nov-2011 18:20:01 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RelRectIng generated by hbm2java
 */
@Entity
@Table(name = "rel_rect_ing", catalog = "cocina")
public class RelRectIngDTO implements java.io.Serializable {

    private static final long serialVersionUID = 4015209316117498519L;

    private Integer idRectIng;
    private RecetaDTO receta;
    private IngredienteDTO ingrediente;

    public RelRectIngDTO() {
    }

    public RelRectIngDTO(final RecetaDTO receta, final IngredienteDTO ingrediente) {
	this.receta = receta;
	this.ingrediente = ingrediente;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id_rect_ing", unique = true, nullable = false)
    public Integer getIdRectIng() {
	return this.idRectIng;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_ing", nullable = false)
    public IngredienteDTO getIngrediente() {
	return this.ingrediente;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_rect", nullable = false)
    public RecetaDTO getReceta() {
	return this.receta;
    }

    public void setIdRectIng(final Integer idRectIng) {
	this.idRectIng = idRectIng;
    }

    public void setIngrediente(final IngredienteDTO ingrediente) {
	this.ingrediente = ingrediente;
    }

    public void setReceta(final RecetaDTO receta) {
	this.receta = receta;
    }

}
